name: "Test scan-action with images"

on: [push]

jobs:
  localbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: "scan-action"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: build flask app
      uses: docker/build-push-action@v2
      with:
        context: ./scan-action/tests/fixtures/localbuild/
        tags: localbuild/testimage:latest
        push: false
        load: true

    - name: Use scan-action to check localbuild
      uses: ./
      with:
        image: "localbuild/testimage:latest"
        fail-build: false
